trigger:
  paths:
    include:
      - vote/*

resources:
  repositories:
    - repository: self

variables:
  - name: dockerRegistryServiceConnection
    value: '6b7a743a-5013-459c-92e1-9b99f1aa6cbe'
  - name: imageRepository
    value: 'vote-app'
  - name: containerRegistry
    value: 'shivacr356.azurecr.io'
  - name: dockerfilePath
    value: '$(Build.SourcesDirectory)/vote/Dockerfile'
  - name: tag
    value: '$(Build.BuildId)'

pool:
  name: "Azure-agent-pool"

stages:
  - stage: Build
    displayName: Build docker image
    jobs:
      - job: Build
        displayName: Build docker image
        steps:
          - task: Docker@2
            displayName: Build docker image
            inputs:
              containerRegistry: '$(dockerRegistryServiceConnection)'
              repository: '$(imageRepository)'
              command: 'build'
              Dockerfile: 'vote/Dockerfile'
              tags: '$(tag)'

  - stage: Push
    displayName: Push docker image
    jobs:
      - job: Push
        displayName: Push docker image
        steps:
          - task: Docker@2
            displayName: Push docker image
            inputs:
              containerRegistry: '$(dockerRegistryServiceConnection)'
              repository: '$(imageRepository)'
              command: 'push'
              tags: '$(tag)'

  - stage: Update
    displayName: Update kubernetes manifest
    jobs:
      - job: Update
        displayName: Update kubernetes manifest
        steps:
          - task: ShellScript@2
            inputs:
              scriptPath: 'scripts/updatek8manifests.sh'
              args: '$(containerRegistry) $(imageRepository) $(tag) vote'
