properties([
    parameters([
        string(
            defaultValue: 'dev',
            name: 'Environment'
        ),
        choice(
            choices: ['plan', 'apply', 'destroy'], 
            name: 'Terraform_Action'
        )])
])
pipeline {
    agent any
    stages {
        stage('Preparing') {
            steps {
                sh 'echo Preparing'
            }
        }
        stage('Git Pulling') {
            steps {
                git branch: 'main', url: 'https://github.com/khannashiv/DevOps-Projects.git'
            }
        }
        stage('Init') {
            steps {
                withAWS(credentials: 'Aws-creds', region: 'us-east-1') {
                sh 'terraform -chdir=Project-3/EKS/ init -reconfigure'
                }
            }
        }
        stage('Validate') {
            steps {
                withAWS(credentials: 'Aws-creds', region: 'us-east-1') {
                sh 'terraform -chdir=Project-3/EKS/ validate'
                }
            }
        }
        stage('Action') {
            steps {
                withAWS(credentials: 'Aws-creds', region: 'us-east-1') {
                    script {    
                        if (params.Terraform_Action == 'plan') {
                            sh "terraform --chdir=Project-3/EKS/ plan -var-file=${params.Environment}.tfvars"
                        }   else if (params.Terraform_Action == 'apply') {
                            sh "terraform --chdir=Project-3/EKS/ apply -var-file=${params.Environment}.tfvars -auto-approve"
                        }   else if (params.Terraform_Action == 'destroy') {
                            sh "terraform --chdir=Project-3/EKS/ destroy -var-file=${params.Environment}.tfvars -auto-approve"
                        } else {
                            error "Invalid value for Terraform_Action: ${params.Terraform_Action}"
                        }
                    }
                }
            }
        }
    }
}